blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: url: https://github.com/mohitahlawat2001/AniNotion/discussions
    about: Please ask questions and start discussions here